version: 2

jobs:
  bionic:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libnetcdf-dev
      - run: swift build
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - bionic